import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export async function getStaticProps() {
  const res = await fetch('http://team2-nextjs-frontend-team2-final-project.itzroks-100000kr1k-fz0n6p-6ccd7f378ae819553d37d5f2ee142bd6-0000.ams03.containers.appdomain.cloud/memes?count=10')
  const memes = await res.json()
  return {
    props: {
      memes,
    },
  }
}

export default function Home({memes}) {
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Hey all
        </h1>
        <div className={styles.gallery}>
        {memes.map((meme) => (
            <img src={meme} className={styles.gallery__img}/>
        ))}
        </div>
      </main>
    </div>
  )
}

