apiVersion: tekton.dev/v1beta1
metadata:
  generateName: nextjs-run
kind: PipelineRun
spec:
  serviceAccountName: build-bot
  pipelineRef:
    name: nextjs
  params:
  - name: app-name
    value: nest-js-app
  - name: source-repo
    value: "https://github.com/julianhahn/nextjs-for-pipeline"
  - name: image-repo
    value: quay.io/mhillb/team2nextjs
  workspaces: 
    - name: output
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 500Mi